services:
  jupyter166:
    image: oklove/jupyter166
    hostname : SG 
##  restart: unless-stopped
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "166:166"
    volumes:
  #   - /data:/data
#     - /:/SG
      - /:/Host
