services:
  host_7788_download:
    image: oklove/webpage_port_7788_download
    container_name: host_7788_download
    ports:
      - "7788:7788"
#     - "78:7788"
#     - "77:7788"
#     - "17:7788"
    volumes:
      - /:/Host
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
